name: travelapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
<<<<<<< HEAD
  image_picker: ^1.0.4  
=======
  image_picker: ^1.0.4
  # State Management
  flutter_riverpod: ^2.5.1
  # PDF Export
  pdf: ^3.10.7
  printing: ^5.12.0
  # CSV Export
  csv: ^5.0.2
  # File handling
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  # Date picker
  intl: ^0.19.0  
>>>>>>> 8b17762 ( expenses module)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
