name: travelapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  shared_preferences: ^2.3.3

  crypto: ^3.0.5
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.2
  path: ^1.8.3
  image_picker: ^1.0.4
  file_selector: ^1.0.1
  http: ^1.2.0
  
  path_provider: ^2.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/config/weather.json

